version: '3.7'
services:
  api:
    build: .
    restart: always
    volumes:
      - .:/api
    command: ./server.py
    ports:
      - 80:3000

  influxdb:
    image: influxdb
    restart: always
    ports: 
      - 8086:8086
    volumes: 
      - influx-data:/var/lib/influxdb

volumes: 
  influx-data:

